# Utiliser l'image de base node:lts-alpine
FROM node:lts-alpine
# Définir le répertoire de travail dans le conteneur
WORKDIR /app-server
# Copier les fichiers package*.json 
COPY package*.json ./
# Installer les dépendances
RUN npm install
# Copier le reste des fichiers du serveur
COPY . .
# Exposer le port 5000
EXPOSE 5000
# Démarrer l'application
CMD ["npm", "start"]